/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardContent: typeof import('./components/CardContent.vue')['default']
    CardHoverOverlay: typeof import('./components/CardHoverOverlay.vue')['default']
    CardImageThumbnail: typeof import('./components/CardImageThumbnail.vue')['default']
    CardTimestamp: typeof import('./components/CardTimestamp.vue')['default']
    ConversationCard: typeof import('./components/ConversationCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
