/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardHoverOverlay: typeof import('./components/CardHoverOverlay.vue')['default']
    CardImageThumbnail: typeof import('./components/CardImageThumbnail.vue')['default']
    CardTimestamp: typeof import('./components/CardTimestamp.vue')['default']
    ConfirmDeleteDialog: typeof import('./components/ConfirmDeleteDialog.vue')['default']
    ConversationCard: typeof import('./components/ConversationCard.vue')['default']
    CreateListingDialog: typeof import('./components/CreateListingDialog.vue')['default']
    CreateMarketItemDialog: typeof import('./components/CreateMarketItemDialog.vue')['default']
    CreateTemplateDialog: typeof import('./components/CreateTemplateDialog.vue')['default']
    ImageDisplay: typeof import('./components/conversation/ImageDisplay.vue')['default']
    InputPanel: typeof import('./components/conversation/InputPanel.vue')['default']
    LibraryDialog: typeof import('./components/conversation/LibraryDialog.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MarketItemCard: typeof import('./components/MarketItemCard.vue')['default']
    PresetCard: typeof import('./components/PresetCard.vue')['default']
    PromptTemplateDialog: typeof import('./components/conversation/PromptTemplateDialog.vue')['default']
    PurchaseDialog: typeof import('./components/PurchaseDialog.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmoothPicture: typeof import('./components/SmoothPicture.vue')['default']
    SnackbarQueue: typeof import('./components/SnackbarQueue.vue')['default']
    TemplateCard: typeof import('./components/TemplateCard.vue')['default']
    TemplateDetailDialog: typeof import('./components/TemplateDetailDialog.vue')['default']
    TimelineStrip: typeof import('./components/conversation/TimelineStrip.vue')['default']
  }
}
